### PR TITLE
Specify BSD as BSD-3-Clause

### LINKED ISSUE #113: License clarification for control_msgs
Hi,

The license is listed as `BSD` in the `package.xml`, but there is no `LICENSE` file provided, and there are [multiple variants of the BSD license](https://en.wikipedia.org/wiki/BSD_licenses) out there.

Can you clarify which BSD license variant `control_msgs` is covered by?

### PR DESCRIPTION
**Pull request by christophfroehlich**
Closes #113

### CODE REVIEW

**Comment by christophfroehlich** [comment]
@mergifyio backport humble

**Review by saikishor — APPROVED** [review]
LGTM

**Review by fmauch — APPROVED** [review]
+1 for specifying this. It was very common in ROS 1 to just say "BSD" which was always annoying.

We could also consider adding a [contributing.txt](https://github.com/ament/ament_lint/blob/rolling/ament_copyright/ament_copyright/template/bsd_3clause_contributing.txt) file to this.

**Review by bmagyar — APPROVED** [review]

**Comment by bmagyar** [comment]
This PR fixed the old setup. We could also consider relicensing them to Apache 2

**Pull request merged**
