### PR TITLE
Added multidof action, msg, srv

### PR DESCRIPTION
**Pull request by hvpandya**
Added 
- MultiDOFFollowJointTrajectory.action
- MultiDOFJointTrajectoryControllerState.msg
- QueryMultiDOFTrajectoryState.srv

to support multi-dof arm joints, planar joints, and floating joints.

### CODE REVIEW

**Comment by davetcoleman** [comment]
This might be a good idea, not sure...

Should the multi-DOF action be combined with the existing [FollowJointTrajectory.action](https://github.com/ros-controls/control_msgs/blob/indigo-devel/control_msgs/action/FollowJointTrajectory.action) instead of creating a second action? Could you give a use case of why you'd want to separate actions? Currently in MoveIt! we have a combined message that is kind of similar to this: [RobotTrajectory.msg](https://github.com/ros-planning/moveit_msgs/blob/indigo-devel/msg/RobotTrajectory.msg). 

The current approach I believe is just to add 6 joints to the regular FollowJointTracjetory if you want a 6dof pose, for example.

**Comment by mikeferguson** [comment]
@davetcoleman we really can't change the FollowJointTrajectoryAction -- it's used pretty much everywhere and this package is > 1.0.

For reference, Ioan created the MultiDoF message in https://github.com/ros/common_msgs/pull/10 (which also has some discussion about this kind of stuff). 

I'd really rather we not add a depend on moveit_msgs for control_msgs (might that even make a circular dependency?)

I hadn't thought about just using 3-6 joints with the slashed namespaces in the FollowJointTrajectory.. that may actually be better than creating yet another message and having to propagate that through the whole release mechanism. I'll discuss that option with @hvpandya

**Comment by davetcoleman** [comment]
I think we could change FollowJointTrajectoryAction in the Jade or future, as long as we only added new fields, not removed/renamed old ones. But I'm sure you want this in Indigo :)

Good point about the MultiDoFJointState. 

I certainly wasn't advocating control_msgs to depend on moveit_msgs, that would be circular indeed.

The 3-6 joints solution is what MoveIt! does frequently internally. 

This PR might be fine - I'm mostly just curious what your thoughts are on a robot with single-dof joints and multi-dof joints: would you have separate action servers for the different parts of the system? Or just use multi-dof joint action for everything?

**Comment by mikeferguson** [comment]
We shouldn't change FollowJointTrajectoryAction in either Indigo or Jade, Kinetic would be the earliest we could change it. Even then, changing FollowJointTrajectoryAction would require a number of downstream changes I think. If we just added a MultiDofJointTrajectory beside the existing JointTrajectory, we could end up in all sorts of horrible places where the number of entries in the two lists are unequal in size. If we want to make a trajectory containing, effectively, RobotTrajectoryPoints (multidof + single dof), then we will end up changing how you index points in the trajectory (requiring code changes in numerous packages).

@davetcoleman one other thing I failed to mention in my comment above, was that the MultiDoF message should also have entries for single joints (as you pointed out as well, we likely want to control everything from the same action server). This would have to be addressed in this PR as well. But as I pointed out above, we probably want something where the messages don't exist yet.

Due to time constraints, I'm inclined to punt on this for now, and use the 3-6 joint solution (in particular, we are only using 3, as the base is constrained to the plane).

**Comment by davetcoleman** [comment]
I think you are definitely right that ROS needs better message support for MultiDOF joints, I don't want to be the one who discourages you guys from adding this feature!

**Comment by bmagyar** [comment]
Kinetic is coming up. What's the current take on this one?

**Comment by DLu** [comment]
@hvpandya Should we close this now that we have #55

**Comment by hvpandya** [comment]
Sounds good @DLu, thanks for putting that together.

**Pull request closed without merging**
