### PR TITLE
Add Dynamic Interface Group Values message

### PR DESCRIPTION
**Pull request by Wiktor-99**
Add interface for gpio controller added in  https://github.com/ros-controls/ros2_controllers/pull/1251

### CODE REVIEW

**Review by christophfroehlich — CHANGES_REQUESTED** [review]
"Component" is the plugin we load.
The official naming is "interface group", see [here](https://github.com/ros-controls/roadmap/blob/master/design_drafts/non_joint_command_interfaces.md).
Is `DynamicInterfaceGroupValues` meaningful and not too long maybe? `component_names` -> `interface_group_names`?

**Comment by Wiktor-99** [comment]
Yes, component could be somehow confusing (I couldn't find better name that would be generic), interface group is ok for me.

**Review by christophfroehlich — APPROVED** [review]
Thanks, LGTM!

**Review by saikishor — APPROVED** [review]

**Comment by saikishor** [comment]
@Mergify.io backport humble

**Comment by saikishor** [comment]
@christophfroehlich should we backport this to Humble?

**Comment by christophfroehlich** [comment]
@mergifyio backport humble

**Pull request merged**
