### PR TITLE
switch to industrial_ci for ROS2

### PR DESCRIPTION
**Pull request by ipa-mdl**
https://github.com/ros-industrial/industrial_ci/issues/390

### CODE REVIEW

**Comment by ipa-mdl** [comment]
https://github.com/ros-controls/control_msgs/pull/31/commits/04c8fd051fcf5171134a0aa04fa5692f0cc450ec could get reverted later

**Comment by ipa-mdl** [comment]
@bmagyar: this tests against testing/shadow-fixed only..

**Comment by DavidMansolino** [comment]
Is there some progress on this front?
If I did understood correctly, this is the last remaining point before being able to release for ROS2 Dashing, right?

**Comment by bmagyar** [comment]
@ipa-mdl why only shadow-fixed? Can we extend now? Can we merge it as-is atm? 
I'd opt for the latter.

**Comment by ipa-mdl** [comment]
> Can we extend now?

Done.

**Pull request merged**
