### PR TITLE
Added controller states feedback for multi dof joints

### PR DESCRIPTION
**Pull request by gstavrinos**

### CODE REVIEW

**Comment by destogl** [comment]
@gstavrinos can you explain a bit motivation and goals of this PR?

**Comment by gstavrinos** [comment]
Of course:

I am building a controller for a quadcopter and using the `FollowJointTrajectory` action to command it through MoveIt. Inside the `FollowJointTrajectory` action I am using the `multi_dof_trajectory` field for the command, but when I have to report the feedback (state) of my controller, the "expected" `multi_dof_trajectory` is not there.

If I wasn't clear enough, please inform me!

**Comment by bmagyar** [comment]
The PR makes sense but the write-up is off a bit. The action feedback actually has those fields,this is a message definition that gets published on the topic interface. It's out of alignment with the action so the fix is completely reasonable. Thanks!

**Review by bmagyar — APPROVED** [review]

**Review by destogl — APPROVED** [review]
@gstavrinos thanks for giving us insight how you are using this.

Would be happy to see also PR on ros2_controller if you decide to open-source your work :) We currently don't have much support for drones, but it is for sure very fascinating 🛩 (cannot find any drone emoji)

**Comment by gstavrinos** [comment]
It will definitely be open source when it's stable enough. I would be more than happy to contribute to ros2_controllers, given that it meets the required standards! :)

(thank you both the for accepted PR)

**Comment by destogl** [comment]
@gstavrinos what about publishing controller :D?

**Comment by gstavrinos** [comment]
Hey Denis, thanks for the interest. The project is currently on hold for about 2 months due to other priorities, but I will eventually get back to it and make it open source as soon as I have a working implementation! :)

**Pull request merged**
