### PR TITLE
Remove action msgs dependency

### PR DESCRIPTION
**Pull request by christophfroehlich**
action_msgs is not needed within this repo.

### CODE REVIEW

**Review by saikishor — CHANGES_REQUESTED** [review]
https://github.com/ros-controls/control_msgs/blob/7c90617377ee385eb51e0585d1461fef851e2f2f/control_msgs/CMakeLists.txt#L13

Can you also remove this line?
Apart from that looks good to me. Thanks for the cleanup.

**Comment by christophfroehlich** [comment]
> Can you also remove this line? Apart from that looks good to me. Thanks for the cleanup.

sure, sorry I forgot that.

**Review by saikishor — APPROVED** [review]
LGTM

**Review by fmauch — APPROVED** [review]
Looks clean to me. 

Simply out of interest: Do you have any source of why that's not needed? I always added it in the past.
I noticed that in the [action tutorial](https://docs.ros.org/en/iron/Tutorials/Intermediate/Creating-an-Action.html) it went away from humble to iron, but it doesn't show in the [Iron release notes](https://docs.ros.org/en/humble/Releases/Release-Iron-Irwini.html). 

More specifically, [this post](https://github.com/ros2/rcl_interfaces/issues/75) suggests that it was indeed needed in the past and then was stripped down to having it in the package.xml was still required.

**Comment by christophfroehlich** [comment]
Phew. I haven't looked that up at all to be honest. I saw no direct dependency in our messages, and it just compiled without.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
