### PR TITLE
Update JTC state message

### PR DESCRIPTION
**Pull request by christophfroehlich**
This implements a state message for JTC following https://github.com/ros-controls/roadmap/pull/57

### CODE REVIEW

**Comment by christophfroehlich** [comment]
I'm not sure how to handle the deprecations here.
I left the old field messages exist (can we delete them in future?).

**Comment by christophfroehlich** [comment]
ok, but humble users can't deactivate the warnings/switch to the new format? humble is LTS, isn't it? 🤔

**Comment by christophfroehlich** [comment]
We could use [get_subscription_count()](https://github.com/ros2/rclcpp/blob/rolling/rclcpp/include/rclcpp/publisher_base.hpp#L134) to deprecate `~/state` and guide users to use `~/controller_state` with the warnings as you suggested. Should we then add the new msg format with a different name, avoiding using the old fields in the `~/controller_state` topic in the meantime?

**Comment by christophfroehlich** [comment]
We decided last WG meeting that we don't want to support the old msg format in rolling/iron. I'll add new PR for humble with proper deprecation warnings.

**Review by bmagyar — APPROVED** [review]

**Pull request merged**
